### ISSUE TITLE
About dataset zerowaste, how can i get it ?

### ISSUE THREAD

**Issue by xuantvvgs** [dbash/zerowaste#1]
Dear dbash,

I am studying for a master's degree. I need your data for my studies and theses. I have submitted a request on the page
https://zenodo.org/record/5717490#.Yd1W2f5ByUk
Hope you can share with me the dataset I use for training the garbage problem

Thank you very much,
Xuan Tr

**Comment by dbash** [comment]
Since we haven't yet published the paper, the dataset is distributed by request only. You should request access on Zenodo using the email address associated with an academic institution.

**Comment by RITESH8055** [comment]
Hi Dina,
I'm Ritesh, final year undergrad student from IIT Madras. I have submitted a request on zenodo for the access of the dataset using my institute email address. Can you please accept my request?. This will be of great help in my research.

Regards,
Ritesh B
