### ISSUE TITLE
Can you please help I'm not understanding how to test the model on custom images? 

### ISSUE THREAD

**Issue by RITESH8055** [dbash/zerowaste#2]
I have gone through the codebase but I could not understand how to run the trained model on custom images. It'll be very helpful if you could guide me.

**Comment by dbash** [comment]
Which model are you referring to?

**Comment by RITESH8055** [comment]
I am trying to test the pretrained DeepLab+MaskRCNN model on custom images, is there any command/steps through which I can do it?

**Comment by dbash** [comment]
[This](https://colab.research.google.com/github/Tony607/detectron2_instance_segmentation_demo/blob/master/Detectron2_custom_coco_data_segmentation.ipynb#scrollTo=9_FzH13EjseR) colab should help you with that. Please let me know if you have any questions.
