### ISSUE TITLE
Regarding zero_waste_w dataset

### ISSUE THREAD

**Issue by bach05** [dbash/zerowaste#4]
Dear authors, 

I am studying some weak supervised and unsupervised techniques to be applied in waste detection. Thank you very much for sharing the zero_waste_w that can be very useful! I was wondering if it possible to perform a sort of time coupling images in "before" and "after". What I would like to obtain is couples of images that are framing the "same conveyor belt portion", before and after human intervention. 

I hope it is clear! Thank you in advance.

**Comment by dbash** [comment]
Hi, thanks for your suggestion, indeed, it would be very useful to have the corresponding frames before and after available. We do not have such data at the moment, but we will keep that in mind and possibly update a synchronized version in the future.
