### ISSUE TITLE
Link to Checkpoints doesn't work

### ISSUE THREAD

**Issue by saurmart** [dbash/zerowaste#9]
Hi, thanks for your great work, I really enjoyed reading it.
While skimming the README, I wanted to take a look at the checkpoints that are provided with links, as I would like to use your pre-trained model for my dataset. Unfortunately, the links no longer work.

**Comment by dbash** [comment]
Are you referring to the following link: http://csr.bu.edu/ftp/recycle/models/ ? It works on my end, please let me know if you cannot open it.

**Comment by saurmart** [comment]
> Are you referring to the following link: http://csr.bu.edu/ftp/recycle/models/ ? It works on my end, please let me know if you cannot open it.

Yes exactly. I get this error:
<img width="349" alt="Not Found Error" src="https://github.com/dbash/zerowaste/assets/67053833/c6fcfad3-3dcd-44ec-b6eb-f2c82926e600">

**Comment by saurmart** [comment]
Hi @dbash, 
thanks for your help, the error was on my end as I was using a plugin to automatically rewrite http to https. Adding an exception for this address solved the problem. Unfortunately, when I tried to access the project again today using http://csr.bu.edu/ftp/recycle/models/, it wasn't possible. I would be very happy if you could check this.

**Comment by dbash** [comment]
What's the error you see when you try to access the link? It works on my end. Please try to open it from another browser and let me know if that doesn't help.

**Comment by saurmart** [comment]
Hi, it's working again, thanks! I got a message from BU that they had an internet outage on campus yesterday, but it has been fixed.
